import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import "./globals.css";
import { Box } from "@mui/material";
import { Header } from "@/components";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AppRouterCacheProvider>
          <Header />
          <Box sx={{ padding: 3 }}>{children}</Box>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
